actions:
  post:
    font-cache-refresh: fc-cache
    reload-xresources: xrdb -merge ~/.Xresources
config:
  backup: true
  create: true
  keepdot: true
  longkey: true
  link_on_import: nolink
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    src: .xinitrc
    dst: ~/.xinitrc
    link: absolute
  d_config_qtile:
    src: .config/qtile
    dst: ~/.config/qtile
    link: absolute
  d_config_zathura:
    src: .config/zathura
    dst: ~/.config/zathura
    link: absolute
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
    link: absolute
  f_xresources:
    src: .Xresources
    dst: ~/.Xresources
    link: absolute
    actions:
    - reload-xresources
  d_local_share_fonts:
    src: .local/share/fonts
    dst: ~/.local/share/fonts
    link: absolute
  d_config_zellij:
    src: .config/zellij
    dst: ~/.config/zellij
    link: absolute
  d_config_alacritty:
    src: .config/alacritty
    dst: ~/.config/alacritty
    link: absolute
  d_config_rofi:
    src: .config/rofi
    dst: ~/.config/rofi
    link: absolute
  d_scripts:
    src: .scripts
    dst: ~/.scripts
    link: absolute
  d_screenlayout:
    src: .screenlayout
    dst: ~/.screenlayout
  d_icons:
    src: .icons
    dst: ~/.icons
    chmod: '700'
  d_config_polybar:
    src: .config/polybar
    dst: ~/.config/polybar
    link: absolute
  f_zsh_aliases:
    src: .zsh_aliases
    dst: ~/.zsh_aliases
    link: absolute
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: absolute
  f_p10k.zsh:
    src: .p10k.zsh
    dst: ~/.p10k.zsh
    link: absolute
  f_zsh_plugins.txt:
    src: .zsh_plugins.txt
    dst: ~/.zsh_plugins.txt
    link: absolute
  d_config_kitty:
    src: .config/kitty
    dst: ~/.config/kitty
    link: absolute
  d_config_dunst:
    src: .config/dunst
    dst: ~/.config/dunst
    link: absolute
  d_config_hypr:
    src: .config/hypr
    dst: ~/.config/hypr
    link: absolute
  d_config_wofi:
    src: .config/wofi
    dst: ~/.config/wofi
    link: absolute
  d_config_waybar:
    src: .config/waybar
    dst: ~/.config/waybar
    link: absolute
  d_config_wlogout:
    src: .config/wlogout
    dst: ~/.config/wlogout
profiles:
  home-pc:
    dotfiles:
    - d_config_rofi
    - f_xinitrc
    - d_config_qtile
    - d_config_zathura
    - f_bashrc
    - f_xresources
    - d_local_share_fonts
    - d_config_zellij
    - d_config_alacritty
    - d_scripts
    - d_screenlayout
    - d_icons
    - d_config_polybar
    - f_zsh_aliases
    - f_p10k.zsh
    - f_zshrc
    - f_zsh_plugins.txt
    - d_config_kitty
    - d_config_dunst
    - d_config_hypr
    - d_config_wofi
    - d_config_waybar
    - d_config_wlogout
  hudson-arco:
    dotfiles:
    - d_screenlayout
