local icons = require('config.icons.nerd')
return {
	'LazyVim/LazyVim',
	opts = {
		icons = {
			diagnostics = {
				Error = icons.DiagnosticError,
				Warn = icons.DiagnosticWarn,
				Hint = icons.DiagnosticHint,
				Info = icons.DiagnosticInfo,
			},
			git = {
				added = icons.GitAdd,
				modified = icons.GitRenamed,
				removed = icons.GitDelete,
			},
			kinds = {
				Array = ' ',
				Boolean = ' ',
				Class = ' ',
				Color = ' ',
				Constant = ' ',
				Constructor = ' ',
				Copilot = ' ',
				Enum = ' ',
				EnumMember = ' ',
				Event = ' ',
				Field = ' ',
				File = ' ',
				Folder = ' ',
				Function = ' ',
				Interface = ' ',
				Key = ' ',
				Keyword = ' ',
				Method = ' ',
				Module = ' ',
				Namespace = ' ',
				Null = 'ﳠ ',
				Number = ' ',
				Object = ' ',
				Operator = ' ',
				Package = ' ',
				Property = ' ',
				Reference = ' ',
				Snippet = ' ',
				String = ' ',
				Struct = ' ',
				Text = ' ',
				TypeParameter = ' ',
				Unit = ' ',
				Value = ' ',
				Variable = ' ',
			},
		},
	},
}
