"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:mauve bg:mauve)\
$os\
[](fg:mauve bg:teal)\
$directory\
[](fg:teal bg:red)\
$git_branch\
[](fg:red bg:peach)\
$git_status\
[](fg:peach bg:green)\
$golang\
$lua\
$nodejs\
$php\
$python\
$rust\
[](fg:green bg:blue)\
$package\
$nix_shell\
[](fg:blue bg:mauve)\
$docker_context\
[ ](fg:mauve)\
$line_break\
$shell\
$character"""

add_newline = true
palette = "catppuccin_mocha"

[os]
disabled = false
style = "fg:crust bg:mauve"


[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)"
style = 'bg:teal fg:crust'
read_only_style = 'bg:mauve fg:crust'
read_only = ' '
truncation_length = 3
truncation_symbol = '../'
use_os_path_sep = false

[git_branch]
symbol = ' '
format = '[[ $symbol$branch](fg:crust bg:red)]($style)'
style = 'bg:peach fg:#000000'

[git_status]
format = '[[( $all_status$ahead_behind )](fg:crust bg:peach)]($style)'
ahead = "↑"
behind = "↓"
style = 'bg:peach'

[username]
format = '[ $user]($style)'
style_root = 'bg:red fg:#000000'
style_user = 'bg:red fg:#000000'

[hostname]
format = '[$ssh_symbol$hostname ]($style)'
style = 'bg:red fg:#000000'
ssh_symbol = '@'

[container]
format = '[$hostname]($style)'
style = 'bg:red fg:#000000'

[sudo]
disabled = false
format = '[$symbol]($style)'
style = 'bg:red fg:#000000'
symbol = '  '



[status]
style = 'bg:yellow fg:#000000'

[c]
format = '[ $symbol($version(-$name)) ]($style)'
style = 'bg:green fg:#000000'

[cmake]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[golang]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[lua]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[nodejs]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[perl]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[php]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[python]
symbol = ' '
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
style = 'bg:green fg:#000000'

[rust]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[package]
symbol = ' '
format = '[ $symbol$version ]($style)'
style = 'bg:blue fg:#000000'

[docker_context]
symbol = ' '
format = '[ $symbol$context ]($style)'
style = 'bg:mauve fg:#000000'

### STATUS INDICATORS

[character]
success_symbol = '[ﬦ](bold cyan)'
error_symbol = '[ﬦ](bold red)'
vimcmd_symbol = '[ﬦ](bold cyan)'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

