- name: Update system
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
- name: Install base packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - rsync
      - man-db
      - man-pages
    state: present
- name: Install shell packages
  become: true
  community.general.pacman:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - quickshell
      - yamlfmt
      - direnv
      - fzf
      - starship
    state: present
- name: Install desktop packages
  become: true
  community.general.pacman:
    name:
      - niri
      - waybar
      - kanshi
      - swaybg
      - swaync
      - libnotify
      - greetd
      - brightnessctl
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
    state: present
- name: Install audio packages
  become: true
  community.general.pacman:
    name:
      - pipewire
      - wireplumber
    state: present
- name: Install applications
  become: true
  community.general.pacman:
    name:
      - neovim
      - btop
      - foot
      - zathura
      - beets
      - unixodbc
    state: present
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: "0644"
    validate: 'visudo -cf %s'
- name: Install AUR packages
  kewlfft.aur.aur:
    use: makepkg
    update_cache: true
    skip_pgp_check: true
    name:
      - 1password
      - 1password-cli
  become: true
  become_user: aur_builder
