---
- name: Install foot
  become: true
  community.general.pacman:
    name: 
      - foot
      - foot-terminfo
    state: present

- name: Ensure foot config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/foot"
    state: directory
    mode: '0755'
- name: Symlink foot config
  ansible.builtin.file:
    src: "{{ role_path }}/files/foot/foot.ini"
    dest: "{{ ansible_facts['user_dir'] }}/.config/foot/foot.ini"
    state: link
    follow: false
- name: Symlink foot theme
  ansible.builtin.file:
    src: "{{ role_path }}/files/foot/gruvbox.ini"
    dest: "{{ ansible_facts['user_dir'] }}/.config/foot/gruvbox.ini"
    state: link
    follow: false
