directory: ~/Music/library
library: ~/Music/library.db
import:
    move: yes
    write: yes
    incremental: yes
    log: beetslog.txt
art_filename: albumart
ui:
    color: yes
paths: 
    default: $albumartist/$album %aunique{}/$track $title %aunique{} 
    singleton: $albumartist/$album %aunique{}/$track $title %aunique{} 
    comp: Compilation/$album %aunique{}/$track $title %aunique{} 
    albumtype:soundtrack: Soundtracks/$album %aunique{}/$track $title %aunique{}

plugins: fetchart embedart lyrics lastgenre rewrite ihate duplicates convert

embedart: 
    remove_art_file: yes 
    auto: yes 
    ifempty: no 
lastgenre: 
    count: 5 
    whitelist: yes 
    min_weight: 10 
    fallback: 
    canonical: no 
    source: album 
    force: yes 
    auto: yes 
    separator: ', ' 
    prefer_specific: no 
fetchart: 
    auto: yes 
    enforce_ratio: no 
    cautious: no 
    cover_names: 
    - cover 
    - front 
    - art 
    - album 
    - folder 
    sources: 
    - filesystem 
    - coverart 
    - itunes 
    - amazon 
    - albumart 
    store_source: no 
rewrite: {} 
duplicates: 
    album: no 
    checksum: '' 
    copy: '' 
    count: no 
    delete: no 
    format: '' 
    full: no 
    keys: [] 
    merge: no 
    move: '' 
    path: no 
    tiebreak: {} 
    strict: no 
    tag: '' 
