return {
	'williamboman/mason.nvim',
	cmd = 'Mason',
	keys = { { '<leader>cm', '<cmd>Mason<cr>', desc = 'Mason' } },
	opts = {
		ui = {
			icons = {
				package_installed = '✓',
				package_pending = '➜',
				package_uninstalled = '✗',
			},
		},
		ensure_installed = {
			'lua-language-server',
			'shellcheck',
			'editorconfig-checker',
			'beautysh',
			'marksman',
			'shfmt',
			'flake8',
			'prettier',
			'prettierd',
			'rust-analyzer',
			'pyright',
			'blue',
			'bash-language-server',
			'rustfmt',
			'typescript-language-server',
			'php-cs-fixer',
			'tailwindcss-language-server',
			'css-lsp',
			'cssmodules-language-server',
			'emmet-language-server',
			'html-lsp',
			'markdownlint',
		},
	},
}
