return {
	'WhoIsSethDaniel/mason-tool-installer.nvim',
	opts = {
		ensure_installed = {
			'stylua',
			'prettier',
			'lua_ls',
			'ts_ls',
			'html',
			'pyright',
			'dockerls',
			'clangd',
			'cmake',
			'clang-format',
			'texlab',
			'docker_compose_language_service',
			'nginx-language-server',
			'bashls',
			'cssls',
			'tailwindcss',
			'rust_analyzer',
			'gopls',
			'intelephense',
		},
		auto_update = true,
		start_delay = 500,
	},
}
