return {
	'nvim-treesitter/nvim-treesitter',
	dependencies = {
		'luckasRanarison/tree-sitter-hypr',
	},
	opts = {
		ensure_installed = {
			'tsx',
			'typescript',
			'php',
			'css',
			'html',
			'markdown',
			'markdown_inline',
		},
		autotag = {
			enable = true,
			enable_rename = true,
			enable_close = true,
			enable_close_on_slash = true,
			filetypes = {
				'html',
				'javascript',
				'typescript',
				'javascriptreact',
				'typescriptreact',
				'svelte',
				'vue',
				'tsx',
				'jsx',
				'rescript',
				'xml',
				'php',
				'markdown',
				'astro',
				'glimmer',
				'handlebars',
				'hbs',
			},
		},
	},
}
