return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"stylua",
			"prettier",
			"lua_ls",
			"ts_ls",
			"html",
			"hyprls",
			"pyright",
			"dockerls",
			"perlnavigator",
			"ols",
			"clangd",
			"clang-format",
			"tinymist",
			"docker_compose_language_service",
			"glsl_analyzer",
			"bashls",
			"cssls",
			"rust_analyzer",
			"twiggy_language_server",
			"intelephense",
		},
		auto_update = true,
		start_delay = 500,
	},
}
