[helpers]

[default]
depends = []

[default.files]
dunst = "~/.config/dunst"
kitty = "~/.config/kitty"
nvim = "~/.config/nvim"
scripts = "~/.config/scripts"
hypr = "~/.config/hypr"
waybar = "~/.config/waybar"
wlogout = "~/.config/wlogout"
wofi = "~/.config/wofi"
lazygit = "~/.config/lazygit"
zathura = "~/.config/zathura"
zellij = "~/.config/zellij"

"gitconfig/gitconfig"= "~/.gitconfig"
"starship/starship.toml" = "~/.config/starship.toml"

fonts = "~/.local/share/fonts"
swaylock = "~/.swaylock"
icons = "~/.icons"
bookmarks = "~/.bookmarks"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/aliases.zsh" = "~/.aliases.zsh"
"zsh/p10k.zsh" = "~/.p10k.zsh"


[default.variables]
