[helpers]

[default]
depends = []

[default.files]
dunst = "~/.config/dunst"
kitty = "~/.config/kitty"
nvim = "~/.config/nvim"
scripts = "~/.config/scripts"
waybar = "~/.config/waybar"
wlogout = "~/.config/wlogout"
wofi = "~/.config/wofi"
lazygit = "~/.config/lazygit"
zathura = "~/.config/zathura"
zellij = "~/.config/zellij"

"gitconfig/gitconfig"= "~/.gitconfig"

fonts = "~/.local/share/fonts"
swaylock = "~/.swaylock"
icons = "~/.icons"
bookmarks = "~/.bookmarks"


[home.files]
"hyprland-home" = "~/.config/hypr"

[work.files]
"hyprland-work" = "~/.config/hypr"

"home/fonts" = "~/.local/share/fonts"
"home/swaylock" = "~/.swaylock"
"home/icons" = "~/.icons"
"home/bookmarks" = "~/.bookmarks"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/aliases.zsh" = "~/.aliases.zsh"
"zsh/p10k.zsh" = "~/.p10k.zsh"


[default.variables]
