[helpers]

[default]
depends = []

[default.files]
dunst = "~/.config/dunst"
kitty = "~/.config/kitty"
nvim = "~/.config/nvim"
scripts = "~/.config/scripts"
hypr = "~/.config/hypr"
sheldon = "~/.config/sheldon"
waybar = "~/.config/waybar"
wlogout = "~/.config/wlogout"
wofi = "~/.config/wofi"
lazygit = "~/.config/lazygit"
zathura = "~/.config/zathura"
zellij = "~/.config/zellij"
fonts = "~/.local/share/fonts"
swaylock = "~/.swaylock"
icons = "~/.icons"
bookmarks = "~/.bookmarks"
cargo = "~/.cargo"

"zsh/zshrc" = "~/.zshrc"
"zsh/aliases.zsh" = "~/.aliases.zsh"

"gitconfig/gitconfig"= "~/.gitconfig"
"starship/starship.toml" = "~/.config/starship.toml"

[default.variables]
